#!/bin/bash
#
# Plugin to monitor rsyncd.
# based on previous work by jintxo
#
# Parameters understood:
#
# 	config   (required)
# 	autoconf (optional)
#
#

mktempfile () {
mktemp -t $1
}       

RSYNCD_LOG=${logfile:-/var/log/rsyncd.log}
LOGTAIL=${logtail:-`which logtail`}
STATEFILE=/var/lib/munin/plugin-state/rsync-bytes.offset

if [ "$1" = "autoconf" ]; then
        if [ -f "${RSYNCD_LOG}" -a -n "${LOGTAIL}" -a -x "${LOGTAIL}" ] ; then
		echo yes
		exit 0
	else
		echo no
		exit 1
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Rsync Server Bytes'
        echo 'graph_args --base 1000 -l 0'
	echo 'graph_order sent recv'
	echo 'graph_category rsync'
	echo 'graph_vlabel Rsync Bytes'
	echo 'sent.label Bytes Sent'
	echo 'recv.label Bytes Recv'
	exit 0
fi

sent=U
recv=U

TEMP_FILE=`mktempfile munin-rsync-bytes.XXXXXX`

if [ -n "$TEMP_FILE" -a -f "$TEMP_FILE" ]
then
	$LOGTAIL ${RSYNCD_LOG} $STATEFILE | grep ".* bytes .* total." > ${TEMP_FILE}
	sent=`grep ' sent .* bytes' ${TEMP_FILE} | awk '{s += $10} END { if ( s ) print s ; else print "0" }'`
	recv=`grep ' recv .* bytes' ${TEMP_FILE} | awk '{s += $10} END { if ( s ) print s ; else print "0" }'`

	/bin/rm -f $TEMP_FILE
fi

echo "sent.value ${sent}"
echo "recv.value ${recv}"


